services:
  addresses-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: addresses-service
    ports:
      - "${SERVER_PORT:-8084}:${SERVER_PORT:-8084}"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - portability_net
networks:
  portability_net:
    external: true
    name: portability_prod
